package com.KeyStone.DeliveryService.ENUM;

public enum Permission {

    // FOR USER
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    VIEW_USER,

    // FOR CUSTOMER
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    VIEW_CUSTOMER,

    // FOR SITE
    CREATE_SITE,
    UPDATE_SITE,
    DELETE_SITE,
    VIEW_SITE,

    // FOR WORK_ORDER 
    CREATE_WORK_ORDER,
    UPDATE_WORK_ORDER,
    DELETE_WORK_ORDER,
    VIEW_WORK_ORDER,
    ASSIGN_WORK_ORDER,
    CLOSE_WORK_ORDER,
    CANCEL_WORK_ORDER,

    // FOR START_WORK
    START_WORK,
    HOLD_WORK,
    RESUME_WORK,
    COMPLETE_WORK,

    RISE_REQUEST,
    VIEW_REQUEST,

    ADD_PARTS,
    UPDATE_PARTS,
    DELETE_PARTS,
    VIEW_PARTS,
    USE_PARTS,

    ADD_TIME_LOGS,
    VIEW_TIME_LOGS,

    SEND_NOTIFICATION,
    VIEW_DASHBOARD,
    VIEW_REPORTS,
    
}
